### ISSUE TITLE
Can't deserialize quotes.

### ISSUE THREAD

**Issue by kewur** [vslee/IEXSharp#112]
Hello,

I am using the StockPrices api to get the quote of a symbol. However it fails with the JsonSerializer exception "Serializer options cannot be changed once serialization or deserialization has occurred."

```
System.InvalidOperationException: Serializer options cannot be changed once serialization or deserialization has occurred.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerOptionsImmutable()
   at System.Text.Json.Serialization.ConverterList.Add(JsonConverter item)
   at IEXSharp.Helper.ExecutorBase.get_JsonSerializerOptions()
   at IEXSharp.Helper.ExecutorREST.ExecuteAsync[ReturnType](String urlPattern, NameValueCollection pathNVC, QueryStringBuilder qsb, Boolean forceUseSecretToken)
   at IEXSharp.Helper.ExecutorREST.SymbolExecuteAsync[ReturnType](String urlPattern, String symbol)
   at IEXSharp.Service.Cloud.CoreData.StockPrices.StockPricesService.QuoteAsync(String symbol)
```

From looking at the docs it looks like this happens when the JsonSerializerOptions is modified after use.

**Comment by kewur** [comment]
just upgraded to 2.9 and no issues. closing

**Comment by kewur** [comment]
I am actually still getting this exception, but I'm not sure if it's something related to my code or is IEXSharp related

```
System.InvalidOperationException: Serializer options cannot be changed once serialization or deserialization has occurred.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerOptionsImmutable()
   at System.Text.Json.JsonSerializerOptions.VerifyMutable()
   at System.Text.Json.Serialization.ConverterList.Add(JsonConverter item)
   at IEXSharp.Helper.ExecutorBase.get_JsonSerializerOptions()
   at IEXSharp.Helper.ExecutorREST.ExecuteAsync[ReturnType](String urlPattern, NameValueCollection pathNVC, QueryStringBuilder qsb, Boolean forceUseSecretToken)
   at IEXSharp.Helper.ExecutorREST.SymbolExecuteAsync[ReturnType](String urlPattern, String symbol)
   at IEXSharp.Service.Cloud.CoreData.StockPrices.StockPricesService.QuoteAsync(String symbol)
```

I am also using System.Json in my code (with different options), but I don't think that should have any bearing on what the library does right?

**Comment by vslee** [comment]
Can you create a small repro?

**Comment by kewur** [comment]
I will try to create something this week

**Comment by Glen1337** [comment]
I am getting this same error as well

**Comment by vslee** [comment]
> I am getting this same error as well

Can you create a small repro?

**Comment by speecesystems** [comment]
I’m embarrassed to say I figured out what my issue was. I hadn’t added
wait() to the asynchronous method call. It didn’t wait.

Thanks
